### ISSUE TITLE
File importation error

### ISSUE THREAD

**Issue by Merchor** [fusioninventory/fusioninventory.github.io#101]
When the try to import a file we get return of "Page not found"
Attached two prints
![Screenshot_2](https://user-images.githubusercontent.com/106624481/174898346-3f7a8454-13e3-44f6-83b6-cd7f19d553f0.png)
![Screenshot_1](https://user-images.githubusercontent.com/106624481/174898347-0a78d37b-5c0e-49d7-95b9-9e65f3682666.png)

**Comment by ddurieux** [comment]
Version of the plugin?

**Comment by ddurieux** [comment]
oh yes, I see the problem, thanks for the report
