### ISSUE TITLE
documentation/agent/installation/android.md

### ISSUE THREAD

**Issue by pVesian** [fusioninventory/fusioninventory.github.io#16]
Hi,

The agent is no longer available on Google Play, the link should be removed.

**Comment by ddurieux** [comment]
You're right, I will begin procedure to re-add it ;)

**Comment by pVesian** [comment]
Hi @ddurieux, where are we on this? Thanks

**Comment by ddurieux** [comment]
For the moment tje apk here: http://forge.fusioninventory.org/projects/android/files
For the new version and published on play, I planned it begin of July 2017

**Comment by g-bougard** [comment]
Hi @pVesian 
the page was fixed as the apk is available in the github release section. Check it again.
You'll see we added also the possibility to participate to the Inventory agent by Flyve MDM beta test. This is an agent fully compliant with FusionInventory.
Thank you for your report.
