### ISSUE TITLE
documentation/agent/installation/android.md

### ISSUE THREAD

**Issue by cr1stt0f3r** [fusioninventory/fusioninventory.github.io#26]
Why is the smartphone added with the application imported into the computer area? And it is not possible to move the device to "phone" ..

**Comment by glpibr** [comment]
@cr1stt0f3r I believe this is a major limitation of GLPi to the present day. It is very important that the possibility of differentiating computers from smartphones.
Maybe it's time for GLPi to contemplate a new IC (mobiles).
The characteristics of these devices are sometimes different from conventional computers. The only similarity I see is the use of applications.

Decent support for these devices can be a major strategic differential for GLPi today compared to other tools on the market.

A major breakthrough would still be the inventory natively supporting the update of geographic coordinates. When the sync is done, send the machine locations to the server with cumulative collections every 1 minute. This would ensure traceability of the device and its path.
- - -
acredito que isso seja uma grande limitação do GLPi para os dias atuais. É muito importante que a possibilidade de difereciar computadores de smartphones.
Talvez seja momento do GLPi contemplar um novo IC (mobiles).
As características destes equipamentos são por vezes diferentes de computadores convencionais. A única similaridade que vejo é a utilização de aplicações.

Suportar decentemente a estes dispositivos pode ser um grande diferencial estratégico para o GLPi nos dias de hoje, se comparado a outras ferramentas no mercado.

Um grande avanço seria ainda o inventário suportar nativamente a atualização de coordenadas geográficas. Quando for feito o sync, enviar para o servidor as localizações do aparelho com coletas acumulativas de 1 em 1 minuto. Isso garantiria a rastreabilidade do dispositivo e de seu trajeto.

**Comment by ddurieux** [comment]
Because smartphone are most a computer than a phone : cpu. memory, softwares (app)...

**Comment by ajsb85** [comment]
@ddurieux I agree

**Comment by glpibr** [comment]
@ddurieux I believe that. But I believe that to improve the level of management it is interesting to create a new category of ICs.
I think of something like "Mobiles." Something different from computers.
- - 
Eu acredito nisso. Mas acredito que para melhorar o nível de gerenciamento é interessante a criação de uma nova categoria de ICs. 
Penso em algo como "Mobiles". Algo diferente de computadores.

**Comment by wawax** [comment]
@glpibr Yes we need to create a new category of items call Smartphones or Mobile devices.
It's not like an IP Phone, and not like a Computer.

This is something we plan to add in a future release in GLPI.

**Comment by g-bougard** [comment]
Hi @cr1stt0f3r 
as said in #28, you opened this issue in the wrong place.
Don't hesitate also to test Flyve inventory agent.
All the team is in the process to enhance the mobile phone support in GLPI as you saw.
Don't hesitate to re-open an issue but in the right place. You can still eventually open on [Fusioninventory for GLPI plugin issue](https://github.com/fusioninventory/fusioninventory-for-glpi/issues) to ask to support for Mobile devices category.
Thank you
