### ISSUE TITLE
Ethernet port address incorrect

### ISSUE THREAD

**Issue by cr1stt0f3r** [fusioninventory/fusioninventory.github.io#27]
Hello, could you check because the registered mobile device is getting the wrong MAC address?

This is generally occurring on Motorola devices such as the Motorola Moto g3 XT1543 and also on the XT1225.
Hope you can help ..

(Mobile connected!)

![image](https://user-images.githubusercontent.com/26659061/28845869-d463d2a6-76df-11e7-9f17-327eef4be45f.png)

**Comment by g-bougard** [comment]
Hi @cr1stt0f3r 
sorry, as said in #28 I think you opened your issue in the wrong place.
Thank you for your report
