### ISSUE TITLE
Problem with importing the same squipment model

### ISSUE THREAD

**Issue by cr1stt0f3r** [fusioninventory/fusioninventory.github.io#28]
After having already imported equipment, when it is done in a second of the same model, the system understands that it is the same device and simply overwrites the equipment register in the system.
No new Agent connection is generated in the plugin.
This fact occurred in the Motorolo Moto G3 XT-1541

Could check it?

**Comment by g-bougard** [comment]
Hi @cr1stt0f3r 
sorry for the delay. Are you talking about a problem while using FusionInventory Agent for Android ?
If yes, you should better open an issue on the [related issues page](https://github.com/fusioninventory/fusioninventory-android/issues).
You may want also to test with Flyve inventory agent which is FusionInventory compatible and in active developement. See the just updated [Android installation page](http://fusioninventory.org/documentation/agent/installation/android.html).

This issue tracker is dedicated to issues on http://fusioninventory.org/
