### ISSUE TITLE
documentation/agent/installation/android.md

### ISSUE THREAD

**Issue by Geeskill** [fusioninventory/fusioninventory.github.io#32]
Hello ! 

I don't find the android app on your links ! 
Is this function still available?

Thanks a lot.

Florian

**Comment by ddurieux** [comment]
The link is here: https://github.com/fusioninventory/fusioninventory-android/releases/download/1.0.1/FusionInventory-1.0.1.apk
We need update the page yes

**Comment by Geeskill** [comment]
Merci pour la réponse rapide ! 
Je vais pouvoir tester ça et proposer la solution fusion-inventory à ma boite ! 

Cordialement

**Comment by g-bougard** [comment]
Hi @Geeskill 
I just fixed the 2 pages. I also added the Flyve Inventory agent which is in beta test. We would appreciate you participate to this beta test ;-)
Thank you
