### ISSUE TITLE
fusioninventory.vbs trying to install 64bit on 32bit machine - http://fusioninventory.org/documentation/agent/installation/windows/fusioninventory.vbs 

### ISSUE THREAD

**Issue by vollkommenIrrelevant** [fusioninventory/fusioninventory.github.io#35]
It seems, that when you give a 64bit installer, the vbs will not check if the machine is 32 or 64 bit.

**Comment by ddurieux** [comment]
Yes it check in the VBS

**Comment by vollkommenIrrelevant** [comment]
but not correct, or?
=> fusionsetupURL links to a 64bit installer

` 
' Verification on OS 32 Bits     
If Fusion <> versionverification Then
   needFusionInstall = True`
=> installation need

`If needFusionInstall() Then
    If (isHttp(fusionsetupURL)) Then
       SaveWebBinary(fusionsetupURL)
       WshShell.Run "CMD.EXE /C %TEMP%\fusioninventory.exe " & fusionarguments,0,True`
=>vba try to install x64 installer on x32 Machine

**Comment by vollkommenIrrelevant** [comment]
I've seen that there is an updated script availiable.
