### ISSUE TITLE
Add information about Camera

### ISSUE THREAD

**Issue by Ivans51** [fusioninventory/fusioninventory.github.io#55]
New tag and information about Camera
In this format:
```XML
<CAMERAS>
	<RESOLUTIONS>4.9 MP (2560x1920)</RESOLUTIONS>
	<LENSFACING>BACK</LENSFACING>
	<FLASHUNIT>1</FLASHUNIT>
	<IMAGEFORMAT>
		<FORMAT>YUV_420_888</FORMAT>
	</IMAGEFORMAT>
	<ORIENTATION>90</ORIENTATION>
	<FOCALLENGTH>3.5 mm</FOCALLENGTH>
        <SENSORSIZE>4.29x3.19</SENSORSIZE>
	<MANUFACTURER>Hynix</MANUFACTURER>
	<RESOLUTIONVIDEO>2.1 MP (1920x1088)</RESOLUTIONVIDEO>
	<MODEL>hi551mipiraw</MODEL>
	<SUPPORT>
		<NAME>gc2355_qunhui_mipi_raw</NAME>
	</SUPPORT>
</CAMERAS>
```
Reference in https://git.io/fANYY

**Comment by g-bougard** [comment]
Hi @Ivans51 

as such spec is not supported in FusionInventory agent and FusionInventory for GLPI plugin, we won't be able to  make accurate specs by ourself.

Could you directly propose an update for the [inventory spec protocol documantation page](https://github.com/fusioninventory/fusioninventory.github.io/blob/master/documentation/dev/spec/protocol/inventory.md) ?

Just for our information, are `<CAMERAS/>` nodes directly handled by [Flyve](https://github.com/flyve-mdm) ?

**Comment by btry** [comment]
And a quick check in GLPI shows we also need to contribute to create a new type of component. Camera does not exists.

**Comment by Ivans51** [comment]
@Naylin15 you can help me here

**Comment by Naylin15** [comment]
Sure, no problem, I'm creating the PR

**Comment by btry** [comment]
hi @Megachip 

I don't think so: the camera we try to handle is a component. 

An IP camera is an asset, not a component. I think that handling IP cameras with Fusion Inventory requires first that GLPI handle such asset. 

It seems there is no such  yet about IP camera on User Echo. https://glpi.userecho.com/#module_23/search/camera You should maybe create it, this would give an idea about how many users need this.

In the mean time, how to inventory an IP camera ? Fusion Inventory needs SNMP to collect information.

**Comment by Megachip** [comment]
@btry You're right. Just an forum entry http://forum.fusioninventory.org/viewtopic.php?id=5620 and an issue #2647 ... will create an Request on user echo too

**Comment by Ivans51** [comment]
Hi, @Naylin15 
This is the information in detail about the nodes of the Camera

```XML
<CAMERAS>
   <!--  Camera resolution, ie '1200x800'  -->
   <RESOLUTIONS>4.9 MP (2560x1920)</RESOLUTIONS>
   <!--  Direction the camera faces relative to device screen -->
   <LENSFACING>BACK</LENSFACING>
   <!--  Whether this camera device has a flash unit -->
   <FLASHUNIT>1</FLASHUNIT>
   <!-- Image output formats -->
   <IMAGEFORMAT>
	<FORMAT>YUV_420_888</FORMAT>
   </IMAGEFORMAT>
   <!-- Orientation camera - Degrees of clockwise rotation -->
   <ORIENTATION>90</ORIENTATION>
   <!-- List of focal lengths - Units in Millimeters -->
   <FOCALLENGTH>3.5 mm</FOCALLENGTH>
   <!-- This is the physical size of the sensor - Units in Millimeters -->
   <SENSORSIZE>4.29x3.19</SENSORSIZE>
   <!-- Name of the Manufacturer -->
   <MANUFACTURER>Hynix</MANUFACTURER>
   <!--  Video Camera resolution, ie '1200x800'  -->
   <RESOLUTIONVIDEO>2.1 MP (1920x1088)</RESOLUTIONVIDEO>
   <!-- Name of the Model -->
   <MODEL>hi551mipiraw</MODEL>
   <!-- List of intefaces and protocols about Camera -->
   <SUPPORT>
	<NAME>gc2355_qunhui_mipi_raw</NAME>
   </SUPPORT>
</CAMERAS>
```

**Comment by Naylin15** [comment]
Thank you @Ivans51

**Comment by g-bougard** [comment]
To follow my #56 PR comment and to respect spec in comment, in @Ivans51 sample,
`<RESOLUTIONS>4.9 MP (2560x1920)</RESOLUTIONS>`
should be replaced by:
`<RESOLUTION>2560x1920</RESOLUTION>`

Also:
`<FOCALLENGTH>3.5 mm</FOCALLENGTH>`
should be replaced by:
`<FOCALLENGTH>3.5</FOCALLENGTH>`
and
`<RESOLUTIONVIDEO>2.1 MP (1920x1088)</RESOLUTIONVIDEO>`
should be replaced by:
`<RESOLUTIONVIDEO>1920x1088</RESOLUTIONVIDEO>`

**Comment by g-bougard** [comment]
Last point, the spec in #56 doesn't show `<IMAGEFORMAT/>` node should include `<FORMAT/>` nodes. You can choice then to replace `<IMAGEFORMAT/>` by `<IMAGEFORMATS/>` and specify in `IMAGEFORMAT+` in `<CAMERAS/>` node spec. and then a sample list could be:
```
...
   <!-- Image output formats -->
   <IMAGEFORMATS>FLEX_RGBA_8888</IMAGEFORMATS>
   <IMAGEFORMATS>FLEX_RGB_888</IMAGEFORMATS>
   <IMAGEFORMATS>YUV_420_888</IMAGEFORMATS>
...
```

There's also the same problem for the `<SUPPORT/>` node. Should it be replaced by `<SUPPORTS/>` ?

**Comment by Ivans51** [comment]
It's fine the changes propose by @g-bougard
And yes, <SUPPORT/> node should it be replaced by <SUPPORTS/>
