### ISSUE TITLE
Install fusioninventory-agent on centos7/HREL7 missing dependencies 

### ISSUE THREAD

**Issue by soklangsum** [fusioninventory/fusioninventory.github.io#67]
HI  guys, 
I have problem with install fusioninventory-agent on centos7/redhat7 with failed dependencies as below:
# yum install fusioninventory-agent  -y
.
.
--> Running transaction check
---> Package avahi-libs.x86_64 0:0.6.31-19.el7 will be installed
---> Package perl-Business-ISBN-Data.noarch 0:20120719.001-2.el7 will be installed
---> Package perl-FusionInventory-Agent.noarch 0:2.5.1-2.el7 will be installed
--> Processing Dependency: perl(File::Copy::Recursive) for package: perl-FusionInventory-Agent-2.5.1-2.el7.noarch
--> Processing Dependency: perl(File::Which) for package: perl-FusionInventory-Agent-2.5.1-2.el7.noarch
---> Package perl-Net-SNMP.noarch 0:6.0.1-7.el7 will be installed
--> Processing Dependency: perl(Crypt::DES) for package: perl-Net-SNMP-6.0.1-7.el7.noarch
--> Finished Dependency Resolution
Error: Package: perl-FusionInventory-Agent-2.5.1-2.el7.noarch (copr:copr.fedorainfracloud.org:trasher:fusioninventory-agent)
           Requires: perl(File::Which)
Error: Package: perl-Net-SNMP-6.0.1-7.el7.noarch (epel)
           Requires: perl(Crypt::DES)
Error: Package: perl-FusionInventory-Agent-2.5.1-2.el7.noarch (copr:copr.fedorainfracloud.org:trasher:fusioninventory-agent)
           Requires: perl(File::Copy::Recursive)
**********************************************************************
Dependency resolving failed due to missing dependencies.
Some repositories on your system are disabled, but yum can enable them
and search for missing dependencies. This will require downloading
metadata for disabled repositories and may take some time and traffic.
**********************************************************************

Event though compile source code installation still error. I cannot find and install dependencies package required. I think it's bugs of Fusioninventory issue.

Anyone can help me?

thanks.

**Comment by g-bougard** [comment]
Hi @soklangsum 
you surely have a mess up in your system, probably in the repositories usage, and this is definitively not the place to request help to fix your system.
