### ISSUE TITLE
documentation/agent/installation/macosx/index.md

### ISSUE THREAD

**Issue by banzo** [fusioninventory/fusioninventory.github.io#8]
Hi, I tried to install the agent on latest OSX, here are the deviations from the installations instructions to get it working, and some feedback:
- agent.cfg is not present in http://prebuilt.fusioninventory.org/stable/macosx-intel/FusionInventory-Agent-2.3.18.pkg.tar.gz but it is in the 2.3.17 package
- I needed to copy manually agent.cfg from the package to /opt/fusioninventory-agent/etc (neither the GUI or command line install did it)
- I could not launch it (`sudo /opt/fusioninventory-agent/fusioninventory-agent` returns `Can't locate FusionInventory/Agent.pm in @INC (...)`) unless I'm in the correct folder: `cd /opt/fusioninventory-agent && sudo /opt/fusioninventory-agent/bin/fusioninventory-agent`, I'm guessing some path issues.
- please comment line `server=https://glpi.inra.fr/glpi/plugins/fusioninventory/` from the agent.cfg (I missed the line and since it is at the end of the file, it overwrote my own server config and probably sent some information to inra)
- how do I uninstall the agent properly?

**Comment by devtom30** [comment]
Hi,

Thank you for reporting these issues.

Sorry for the late answer. We have been busy and that's true we have to look this repository's issues more often.
If you want to report an issue concerning the FusionInventory Agent, please post your issue in the Agent's repository section, here : https://github.com/fusioninventory/fusioninventory-agent

Thank you.

**Comment by devtom30** [comment]
Concerning the issues,

- The file agent.cfg is present in etc directory, inside the agent's root directory.

- see preceding

- That's true, to launch the agent, you have to chdir into agent's directory. You can launch it from a different directory but you have to give to perl interpreter the path to lib dir using -I option, and you have to give the path to configuration file (agent.cfg), and other paths. See in bin/fusioninventory-agent file, the variable %setup for implementation details.
I think it's far more easy to just chdir into Agent's dir.

- The line is not present in agent.cfg file included in package

- To uninstall, once you have stopped the process, you can just delete the directory /opt/fusioninventory-agent

Hope this will help. If you have any comment, don't hesitate. Have a nice day!

Regards,
Thomas

**Comment by g-bougard** [comment]
Hi @banzo 
[FusionInventory Agent 2.3.21](https://github.com/fusioninventory/fusioninventory-agent/releases/tag/2.3.21) is now released. It includes a fresh MacOSX package with updated perl since 2.3.17/2.3.18.
Your issues should not concern this latest release but feel free to open a new issue.
Thank you for your involvement
