### ISSUE TITLE
Link to "FusionInventory users community forum" on http://fusioninventory.org/resources/ is leads to page with invalid certificate

### ISSUE THREAD

**Issue by fthommen** [fusioninventory/fusioninventory.github.io#83]
The link to the "FusionInventory users community forum" (https://forum.fusioninventory.org/) on http://fusioninventory.org/resources/ leads to a page with an invalid certificate (the certificate is only valid for david.durieux.family)

**Comment by fthommen** [comment]
...and there is no forum there anyway... So basically the link is broken.

**Comment by ddurieux** [comment]
The forum has been shutdwon couple weeks due to spams.
It will be back soon, but no date to give

**Comment by fthommen** [comment]
ok I understand, thx.  But where are users supposed to get help in the meantime? The forum is down and the maillist doesn't seem to be very active...

**Comment by kintaro1981** [comment]
try to migrate fo xenforo
it has strong antispam feature

**Comment by ddurieux** [comment]
both solutions take times, I prefer use my own method, the spam will be nicely blocked ;)

**Comment by kintaro1981** [comment]
In the telegram group I suggested this some months ago, take a look at it and good work!

https://docs.mybb.com/1.8/administration/spam/
https://community.mybb.com/mods.php?action=browse&category=27

**Comment by ddurieux** [comment]
The forum is no longer exists
