### ISSUE TITLE
fusioninventory-esx package is accessible via official website 

### ISSUE THREAD

**Issue by vazome** [fusioninventory/fusioninventory.github.io#94]
On the reference page
http://fusioninventory.org/documentation/references/

The link of 2.3.x (stable) fusioninventory-esx is not available http://fusioninventory.org/documentation/references/agent/2.3.x/fusioninventory-esx.html

**Comment by vazome** [comment]
as well as other links on that page

**Comment by ddurieux** [comment]
Seems this page must be deleted, replaced by the man page: http://fusioninventory.org/documentation/agent/man/

**Comment by vazome** [comment]
@ddurieux sure but I cannot find download links on that new man page too

**Comment by ddurieux** [comment]
download links? 
You have the ESX link on the page (and works), for example: http://fusioninventory.org/documentation/agent/man/fusioninventory-esx.html

**Comment by vazome** [comment]
@ddurieux I found ESX package under "debian based" manual 

http://fusioninventory.org/documentation/agent/installation/linux/deb.html
![image](https://user-images.githubusercontent.com/46573198/140608463-da0b6afd-584c-48a9-8570-9b052672017d.png)

It's good now!
